import type { ReactElement } from "react";
import { SceneFrame } from "./sceneFrame";
import { LiveOnly } from "./printContext";
import styles from "./Lecture.module.css";

export function CoverScene(): ReactElement {
  return (
    <section className={`${styles.scene} ${styles.cover}`} id="cover">
      <div className={styles.coverInner}>
        <p className={styles.kicker}>School of Data Science · CUHK-Shenzhen</p>
        <h1 className={styles.coverTitle}>Studying at SDS: What and Why</h1>
        <p className={styles.lead}>
          Before choosing a major, it helps to understand what data science is, why the
          curriculum is designed this way, and what kinds of abilities it is meant to build.
        </p>
        <div className={styles.pills}>
          <span className={styles.pill}>Curiosity</span>
          <span className={styles.pill}>Data</span>
          <span className={styles.pill}>Models</span>
          <span className={styles.pill}>Computing</span>
          <span className={styles.pill}>Real-world decisions</span>
        </div>
        <LiveOnly>
          <p className={styles.hint}>Use ← → or the buttons above.</p>
        </LiveOnly>
      </div>
    </section>
  );
}

export function StartingPointScene(): ReactElement {
  return (
    <SceneFrame kicker="Starting point" title="You chose SDS for a reason">
      <p className={styles.lead}>
        Maybe you are interested in AI, programming, mathematics, business analytics, social
        issues, or simply the idea that data is changing the world.
      </p>
      <div className={styles.three}>
        <article className={styles.card}>
          <p className={styles.kicker}>Interest</p>
          <h2 className={styles.cardTitle}>Curiosity is already there</h2>
          <p className={styles.muted}>
            You already have some curiosity about data, technology, or complex problems.
          </p>
        </article>
        <article className={styles.card}>
          <p className={styles.kicker}>Uncertainty</p>
          <h2 className={styles.cardTitle}>The name can still feel vague</h2>
          <p className={styles.muted}>
            At the same time, “data science” may still feel broad, vague, or even mysterious.
          </p>
        </article>
        <article className={styles.card}>
          <p className={styles.kicker}>Direction</p>
          <h2 className={styles.cardTitle}>Turn interest into a map</h2>
          <p className={styles.muted}>
            Today’s goal is to turn vague interest into a clearer understanding of possible paths.
          </p>
        </article>
      </div>
      <p className={styles.quote}>
        A good university curriculum is not just a list of courses. It is a carefully designed
        path for building abilities.
      </p>
    </SceneFrame>
  );
}

export function DefinitionScene(): ReactElement {
  return (
    <SceneFrame kicker="Definition" title="What is Data Science?">
      <p className={styles.lead}>
        Data science is the study and practice of extracting knowledge, building models, making
        predictions, and supporting decisions from data.
      </p>
      <div className={styles.tableWrap}>
        <table className={styles.proseTable}>
          <thead>
            <tr>
              <th>Core element</th>
              <th>What it means</th>
              <th>Example questions</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <strong>Data</strong>
              </td>
              <td>Records generated by people, systems, devices, and the natural world.</td>
              <td>What data do we have? Is it reliable?</td>
            </tr>
            <tr>
              <td>
                <strong>Models</strong>
              </td>
              <td>Mathematical or computational representations of patterns.</td>
              <td>Can we predict, classify, explain, or recommend?</td>
            </tr>
            <tr>
              <td>
                <strong>Inference</strong>
              </td>
              <td>Reasoning from limited and imperfect data.</td>
              <td>Is this pattern real, or just random noise?</td>
            </tr>
            <tr>
              <td>
                <strong>Decision</strong>
              </td>
              <td>Using analysis to guide action in the real world.</td>
              <td>What should we do next?</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p className={styles.note}>
        Data science is not merely “using software” or “running algorithms.” It is a way of
        understanding the world through data.
      </p>
    </SceneFrame>
  );
}

export function PerspectivesScene(): ReactElement {
  return (
    <SceneFrame kicker="Two perspectives" title="Data Science as a subject and as a career">
      <div className={styles.three}>
        <article className={styles.card}>
          <p className={styles.kicker}>Academic subject</p>
          <h2 className={styles.cardTitle}>Understand principles</h2>
          <ul>
            <li>Why does a model work?</li>
            <li>What assumptions are being made?</li>
            <li>How can methods be improved?</li>
          </ul>
        </article>
        <article className={styles.card}>
          <p className={styles.kicker}>Career field</p>
          <h2 className={styles.cardTitle}>Solve real problems</h2>
          <ul>
            <li>How can data improve a product?</li>
            <li>How do we build a usable system?</li>
            <li>How do results influence decisions?</li>
          </ul>
        </article>
        <article className={styles.card}>
          <p className={styles.kicker}>Transferable ability</p>
          <h2 className={styles.cardTitle}>Think with data</h2>
          <ul>
            <li>Define problems clearly.</li>
            <li>Analyze evidence carefully.</li>
            <li>Communicate conclusions responsibly.</li>
          </ul>
        </article>
      </div>
      <p className={styles.quote}>Tools change. Platforms change. Fundamental abilities last much longer.</p>
    </SceneFrame>
  );
}

export function CurriculumWhyScene(): ReactElement {
  return (
    <SceneFrame kicker="Curriculum design" title="Why do we learn so many different courses?">
      <p className={styles.lead}>
        The curriculum may look broad, but it is broad for a reason: real data problems require
        several kinds of knowledge working together.
      </p>
      <div className={styles.tableWrap}>
        <table className={styles.proseTable}>
          <thead>
            <tr>
              <th>Course area</th>
              <th>What you learn</th>
              <th>Why it matters</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <strong>Mathematics</strong>
              </td>
              <td>Calculus, linear algebra, probability, optimization</td>
              <td>Provides the language for structure, change, uncertainty, and models.</td>
            </tr>
            <tr>
              <td>
                <strong>Statistics</strong>
              </td>
              <td>Inference, regression, experiments, uncertainty</td>
              <td>Helps judge whether conclusions are reliable.</td>
            </tr>
            <tr>
              <td>
                <strong>Computer Science</strong>
              </td>
              <td>Programming, algorithms, databases, systems</td>
              <td>Makes it possible to process data and implement methods at scale.</td>
            </tr>
            <tr>
              <td>
                <strong>Applications</strong>
              </td>
              <td>Projects, case studies, domain problems</td>
              <td>Connects technical methods to real-world value.</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p className={styles.note}>
        The courses are not isolated boxes. Together, they form a complete ability chain.
      </p>
    </SceneFrame>
  );
}

export function WorkflowScene(): ReactElement {
  return (
    <SceneFrame kicker="A complete workflow" title="How does a data science problem actually work?">
      <p className={styles.lead}>
        Consider a familiar example: predicting which students may need academic support early, so
        that the university can offer help before problems become serious.
      </p>
      <div className={styles.flow}>
        <div className={styles.flowStep}>Define the problem</div>
        <div className={styles.flowArrow}>→</div>
        <div className={styles.flowStep}>Collect data</div>
        <div className={styles.flowArrow}>→</div>
        <div className={styles.flowStep}>Clean &amp; explore</div>
        <div className={styles.flowArrow}>→</div>
        <div className={styles.flowStep}>Build models</div>
        <div className={styles.flowArrow}>→</div>
        <div className={styles.flowStep}>Evaluate results</div>
        <div className={styles.flowArrow}>→</div>
        <div className={styles.flowStep}>Support decisions</div>
      </div>
      <div className={styles.three}>
        <article className={styles.card}>
          <h2 className={styles.cardTitle}>Not just “run a model”</h2>
          <p className={styles.muted}>
            The hard part often begins before modeling: defining the right question and
            understanding the data.
          </p>
        </article>
        <article className={styles.card}>
          <h2 className={styles.cardTitle}>Not just “get accuracy”</h2>
          <p className={styles.muted}>
            We also ask whether the result is stable, fair, interpretable, and useful.
          </p>
        </article>
        <article className={styles.card}>
          <h2 className={styles.cardTitle}>Not just “finish an assignment”</h2>
          <p className={styles.muted}>
            Real projects require judgment, communication, and responsibility.
          </p>
        </article>
      </div>
    </SceneFrame>
  );
}

export function AbilitiesScene(): ReactElement {
  return (
    <SceneFrame kicker="Learning outcomes" title="What abilities are we trying to build?">
      <div className={styles.three}>
        <article className={styles.card}>
          <div className={styles.num}>01</div>
          <h2 className={styles.cardTitle}>Abstraction</h2>
          <p className={styles.muted}>
            Turn messy real-world questions into clear analytical or computational problems.
          </p>
        </article>
        <article className={styles.card}>
          <div className={styles.num}>02</div>
          <h2 className={styles.cardTitle}>Inference</h2>
          <p className={styles.muted}>
            Reason carefully from incomplete, noisy, and sometimes biased data.
          </p>
        </article>
        <article className={styles.card}>
          <div className={styles.num}>03</div>
          <h2 className={styles.cardTitle}>Computation</h2>
          <p className={styles.muted}>
            Use programming, algorithms, and systems to work with data effectively.
          </p>
        </article>
      </div>
      <div className={styles.two}>
        <article className={styles.card}>
          <div className={styles.num}>04</div>
          <h2 className={styles.cardTitle}>Modeling</h2>
          <p className={styles.muted}>
            Build, train, test, and improve models for prediction, explanation, or decision
            support.
          </p>
        </article>
        <article className={styles.card}>
          <div className={styles.num}>05</div>
          <h2 className={styles.cardTitle}>Communication</h2>
          <p className={styles.muted}>
            Explain findings clearly, responsibly, and persuasively to different audiences.
          </p>
        </article>
      </div>
    </SceneFrame>
  );
}

export function PathsScene(): ReactElement {
  return (
    <SceneFrame kicker="From one field to multiple paths" title="Data Science is not a single track">
      <p className={styles.lead}>
        Students in the same school can develop different strengths. The three majors share
        foundations, but emphasize different questions.
      </p>
      <div className={styles.tableWrap}>
        <table className={styles.proseTable}>
          <thead>
            <tr>
              <th>Path</th>
              <th>Core concern</th>
              <th>Typical student interest</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <strong>Statistics</strong>
              </td>
              <td>Uncertainty, inference, evidence, explanation, causality</td>
              <td>“Is this conclusion trustworthy?”</td>
            </tr>
            <tr>
              <td>
                <strong>Computer Science</strong>
              </td>
              <td>Algorithms, systems, software, intelligent computation</td>
              <td>“How can we build it efficiently and reliably?”</td>
            </tr>
            <tr>
              <td>
                <strong>Big Data</strong>
              </td>
              <td>Data engineering, platforms, scale, real-world applications</td>
              <td>“How can massive data be organized, processed, and used?”</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p className={styles.note}>
        Choosing a major is not simply asking “Which one is best?” It is asking “Which ability do
        I want to develop most deeply?”
      </p>
    </SceneFrame>
  );
}

export function SelfAskScene(): ReactElement {
  return (
    <SceneFrame kicker="Self-assessment" title="Before choosing a major, ask yourself">
      <div className={styles.split}>
        <div>
          <article className={styles.card}>
            <p className={styles.kicker}>Reliability</p>
            <h2 className={styles.cardTitle}>Do I enjoy asking whether a conclusion is reliable?</h2>
            <p className={styles.muted}>
              Look closely at statistics, inference, experiments, and causal reasoning.
            </p>
          </article>
          <article className={styles.card} style={{ marginTop: 16 }}>
            <p className={styles.kicker}>Building</p>
            <h2 className={styles.cardTitle}>Do I enjoy building algorithms, software, or systems?</h2>
            <p className={styles.muted}>
              Look closely at computer science, programming, algorithms, and intelligent systems.
            </p>
          </article>
          <article className={styles.card} style={{ marginTop: 16 }}>
            <p className={styles.kicker}>Real data</p>
            <h2 className={styles.cardTitle}>Do I enjoy working with large, messy, real-world data?</h2>
            <p className={styles.muted}>
              Look closely at big data, data engineering, platforms, and applied data projects.
            </p>
          </article>
        </div>
        <div>
          <h2 className={styles.cardTitle}>Pay attention to your learning experience</h2>
          <ul>
            <li>Which problems make you curious?</li>
            <li>Which difficult courses are you willing to spend time on?</li>
            <li>Where do you feel progress and achievement?</li>
            <li>What kind of work do you imagine doing for years, not just weeks?</li>
          </ul>
          <p className={styles.note}>
            First year is not about labeling yourself too early. It is about observing your
            interests, strengths, and willingness to grow.
          </p>
        </div>
      </div>
    </SceneFrame>
  );
}

export function TransitionScene(): ReactElement {
  return (
    <SceneFrame kicker="Transition" title="Now we are ready to discuss the three majors" tone="dark">
      <p className={styles.lead}>
        We have seen that data science is an ability system built from mathematics, statistics,
        computing, modeling, and real-world applications.
      </p>
      <div className={styles.three}>
        <article className={styles.card}>
          <h2 className={styles.cardTitle}>Statistics</h2>
          <p className={styles.muted}>
            Reasoning under uncertainty and drawing reliable conclusions from data.
          </p>
        </article>
        <article className={styles.card}>
          <h2 className={styles.cardTitle}>Computer Science</h2>
          <p className={styles.muted}>
            Building algorithms, systems, and intelligent computational tools.
          </p>
        </article>
        <article className={styles.card}>
          <h2 className={styles.cardTitle}>Big Data</h2>
          <p className={styles.muted}>
            Managing, processing, and applying data at scale in real-world contexts.
          </p>
        </article>
      </div>
      <p className={styles.quote}>
        The next question is not “Which major is better?” It is “Which direction best matches my
        curiosity, strengths, and future development?”
      </p>
    </SceneFrame>
  );
}
